[tools]
# cargo-binstall = "1.20.1"		# (only used to install tracey)
# https://tracey.bearcove.eu/
# "cargo:tracey" = "2.0.0" # 2.0.0[-rc] is not released yet, so we have to build from source for now
# "cargo:https://github.com/bearcove/tracey" = { version = "rev:7494469c454ea3e93203f2cc860adbf153fe64b9", crate = "tracey" }
# for compiling tracey, until 2.0 is released
node = "26"
pnpm = "11.11.0"
# for compiling tracey, until 2.0 is released
rust = { version = "1.98.0-beta.1", profile = "minimal" }

[settings]
auto_install = false

[tasks]
"tracey:install" = "cargo install --git https://github.com/beeequeue/tracey --rev 48e9a3af8bb757a6083e2ff4c6973cc0ccce90f6 tracey"
"tracey:export" = "tracey export --public-path /standardglob/ dist/website"
