name: tests

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/tests.yml
      - tests/*.yml
      - tests/js/**
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - tests/*.yml
      - tests/js/**
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: website-${{ github.ref }}
  cancel-in-progress: true

jobs:
  js:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install dependencies' dependencies
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          version: 2026.7.5
          install: true
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install dependencies
        working-directory: tests/js
        run: node --run test
